# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoredups:ignorespace

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias rm='rm -rf'
alias cp='cp -i'
alias mv='mv -i'
alias cls='clear'
alias getsize='du -h -s --apparent-size'
alias showzombie='ps -ef | grep 'Z''
alias pp='/home/p12478/pp'
alias pf='cm update . --override'
alias iexplore='nabi & firefox'
alias pmm='/home/p12478/pmm'
alias g='gcc -o'

#alias lu='/home/p12478/Lua_workspace/lua-5.2.2/src/lua'
# Command List

# add sudo user
# vi /etc/sudoers
# p12478 ALL=(ALL) ALL

# To get size specific account or directory
# du -h -s --apparent-size ./aaa/

# kill specific account
# ps -ef|grep account
# kill -9 xxxx

# Find file
# 1. Current directory
# find -name '*.pl'
# find [where] -name '[file name]
# fine -name '[filename]'

# remove specific file in folder
# find ./ -name "filename" -exec rm -f {} \;


# Search keyword in files
# grep <keyword> ./ -R

# grep ignore upper/ lower
# grep -i <keyword>

# grep or option
# grep -E "<Keyword>|<keyword>"


# date setting
# /usr/bin/rdate -s zero.bora.net

# samba setting
#
# add
# smbpasswd -a id
#
# delete
# smbpasswd -x id
#
# change smb password
# smbpasswd
#
# smb setting
# vi /etc/samba/smb.conf
#
# restart
# /etc/init.d/samba restart

# svn subversion
# apt-get install subversion
# mkdir svn-repos
# svnadmin create /home/svn-repos
# svnserve -d -r /home/svn-repos

# zombie process
#
# show zombie
# ps -el | grep 'Z'
#
# kill zombie
# kill -9 <PID>

# useful
# top
# w
# finger

# ssh fast login
# /etc/ssh/sshd_config
# EOF -> add > UseDNS=no
# /etc/init.d/ssh restart
# or service ssh restart

# tab reset command
# retab

# vi window divide
# sp/ vs
# move window 
# ctrl + w + w


# vi search and replace line
# :/s/OLD/NEW
# vi search and replace line all
# :/s/OLD/NEW/g
# vi search and replace all in file
# :%s/OLD/NEW/g


# mmm build
# source build/envsetup.sh
# export OEM_PRODUCT_BRAND=SKY
# choosecombo
# mmm packages/apps/Settings

# tar 
# tar -cvf x.tar x
# tar -xvf x.tar

# tar gz
# tar -zcvf x.tar.gz x
# tar -zxvf x.tar


# ctags
# +sync 
#  ctags -R directory
# +use
#  in vi
#  :ts keyword
#  ctrl + ]  =>  forward
#  ctrl + t  =>  back
#
#  :ta /keywork

# android version info
# build/core/version_defaults.mk



#export LANG=C
#export LANG="ko_KR.eucKR"
#export LC_ALL=C
#export PATH=$PATH:/opt/rational/clearcase/bin:$PATH:.
#export JAVA_HOME=/pkg/jdk/jdk1.5.0_22
export LUA_HOME=/home/p12478/Lua_workspace/lua-5.2.
export JAVA_HOME=/pkg/jdk/jdk1.6.0_26
export GIT_HOME=/home/p12478/bin
#export PATH=$JAVA_HOME:$JAVA_HOME/bin:$JAVA_HOME/jre/bin:$LUA_HOME/src:$PATH:.
#export PATH=$JAVA_HOME:$JAVA_HOME/bin:$JAVA_HOME/jre/bin:$LUA_HOME/src:$PATH:.:$PATH
export PATH=/opt/plasticscm4/client:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/usr/games:$JAVA_HOME:$JAVA_HOME/bin:$JAVA_HOME/jre/bin:$LUA_HOME/src:$GIT_HOME:$PATH:.

#export PATH=$JAVA_HOME/bin:$JAVA_HOME/jre/bin:$PATH
#export PYTHON_PATH=/pkg/python/2.4.3/bin
export CPUCORENUM=24
#export ANDROID_BUILD_SHELL=/bin/bash



# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi
alias ct='/usr/atria/bin/cleartool'
alias xcc='/usr/atria/bin/xclearcase &'
alias cpe='/usr/atria/bin/clearprojexp &'
alias plastic='plastic &'
export LANG=ko_KR.UTF8
export XMODIFIERS="@im=nabi"
export HANGUL_KEYBOARD_TYPE=2
#export PATH=/opt/plasticscm4/client:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/usr/games:$JAVA_HOME:$JAVA_HOME/bin:$JAVA_HOME/jre/bin:$LUA_HOME/src:$GIT_HOME::$PATH:.

umask 002
